select
    season,
    round,
    race_name,
    'R' || lpad(cast(round as varchar), 2, '0') || ' · '
        || replace(race_name, ' Grand Prix', '') as race_label,
    driver_code,
    driver_name,
    team,
    stop_number,
    actual_pit_lap,
    actual_out_lap,
    pit_duration_sec,
    official_pit_match,
    old_stint,
    new_stint,
    old_compound,
    new_compound,
    new_tyre_fresh,
    window_start_lap,
    window_end_lap,
    best_supported_shift_laps,
    best_hypothetical_pit_lap,
    estimated_gain_vs_actual_sec,
    best_delta_p25_sec,
    best_delta_p75_sec,
    best_shift_win_pct,
    best_earlier_delta_sec,
    best_later_delta_sec,
    supported_scenarios,
    old_reference_laps,
    new_mature_reference_laps,
    warmup_profile_laps,
    old_slope_sec_per_tyre_lap,
    new_slope_sec_per_stint_lap,
    old_model_mad_sec,
    new_model_mad_sec,
    replay_coverage_pct,
    field_peer_count_median,
    timing_signal,
    eligible,
    exclusion_reason,
    confidence,
    methodology_version
from marts.pit_timing_sensitivity

union all
select
    0, 0, '__NO_DATA__', 'R00 · No data', '__NO_DATA__', '__NO_DATA__',
    '__NO_DATA__', 0, 0, 0, cast(null as double), false, 0, 0,
    '__NO_DATA__', '__NO_DATA__', false, 0, 0, cast(null as integer),
    cast(null as integer), cast(null as double), cast(null as double),
    cast(null as double), cast(null as double), cast(null as double),
    cast(null as double), 0, 0, 0, 0, cast(null as double), cast(null as double),
    cast(null as double), cast(null as double), cast(null as double),
    cast(null as double), 'Insufficient evidence', false, 'No data',
    'insufficient', 'pit-timing-sensitivity-v1'
where not exists (select 1 from marts.pit_timing_sensitivity)
order by season, round, driver_code, stop_number
