select
    season,
    round,
    race_name,
    'R' || lpad(cast(round as varchar), 2, '0') || ' · '
        || replace(race_name, ' Grand Prix', '') as race_label,
    battle_id,
    battle_number,
    attacker_code,
    attacker_name,
    attacker_team,
    defender_code,
    defender_name,
    defender_team,
    same_team,
    start_t_s,
    end_t_s,
    duration_s,
    pressure_seconds,
    contact_seconds,
    start_lap,
    end_lap,
    laps_spanned,
    position_contested,
    valid_samples,
    pressure_samples,
    coverage_pct,
    same_lap_deficit_share_pct,
    min_gap_s,
    median_gap_s,
    outcome,
    terminal_reason,
    converted,
    defender_retained,
    pass_t_s,
    pass_lap,
    time_to_pass_s,
    overtake_confidence,
    overtake_reason,
    quick_reversal,
    reversal_t_s,
    eligible,
    exclusion_reason,
    confidence,
    methodology_version
from marts.racecraft_battles

union all
select
    0, 0, '__NO_DATA__', 'R00 · No data', '__NO_DATA__', 0,
    '__NO_DATA__', '__NO_DATA__', '__NO_DATA__', '__NO_DATA__',
    '__NO_DATA__', '__NO_DATA__', false,
    cast(null as double), cast(null as double), cast(null as double),
    cast(null as double), cast(null as double), cast(null as integer),
    cast(null as integer), cast(null as integer), cast(null as integer),
    cast(null as integer), cast(null as integer), cast(null as double),
    cast(null as double), cast(null as double), cast(null as double),
    'Unavailable', 'no_data', false, false, cast(null as double),
    cast(null as integer), cast(null as double), cast(null as double),
    'No data', false, cast(null as double), false, 'No data',
    'insufficient', 'racecraft-v1'
where not exists (select 1 from marts.racecraft_battles)
order by season, round, battle_number
