select
    season,
    round,
    race_name,
    'R' || lpad(cast(round as varchar), 2, '0') || ' · '
        || replace(race_name, ' Grand Prix', '') as race_label,
    event_id,
    event_number,
    event_type,
    driver_code,
    driver_name,
    team,
    position_before,
    position_after,
    positions_gained,
    gap_to_leader_before_s,
    gap_to_leader_after_s,
    raw_gap_gain_s,
    field_adjusted_gap_gain_s,
    lap_before,
    lap_after,
    lap_deficit_before,
    lap_deficit_after,
    lap_deficit_changed,
    stint_before,
    stint_after,
    compound_before,
    compound_after,
    tyre_life_before,
    tyre_life_after,
    pitted_during_intervention,
    pitted_during_recovery,
    stop_count,
    tyre_changed_during_suspension,
    active_after,
    eligible,
    exclusion_reason,
    confidence,
    outcome_label,
    timing_before_offset_s,
    timing_after_offset_s,
    methodology_version
from marts.race_control_impact

union all
select
    0, 0, '__NO_DATA__', 'R00 · No data', '__NO_DATA__', 0, 'No event',
    '__NO_DATA__', 'No driver', 'No team',
    cast(null as integer), cast(null as integer), cast(null as integer),
    cast(null as double), cast(null as double), cast(null as double), cast(null as double),
    cast(null as integer), cast(null as integer), cast(null as integer), cast(null as integer),
    false,
    cast(null as integer), cast(null as integer), '', '',
    cast(null as integer), cast(null as integer),
    false, false, 0, false, false, false,
    'No data', 'Low', 'Excluded',
    cast(null as double), cast(null as double), 'race-control-impact-v1'
where not exists (select 1 from marts.race_control_impact)
order by season, round, event_number, position_before
